# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Deploy and publish
run-name: Deploy and publish Cinnamon into npm
on:
  push:
    tags:
      - '**'
jobs:
  build-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build-lib
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
